### ISSUE TITLE
the result of labelling file is all 0

### ISSUE THREAD

**Issue by junchen14** [ML-KULeuven/SAR-PU#1]
hi I wanna use your model as a baseline
after i tries with my data (basically the data is the word embedding file)
the generated labelling file are all 0
I don't know why that happens, could you give me some hints why that happen?

**Comment by jessa** [comment]
Could you describe your setting a bit more clearly?

**Comment by junchen14** [comment]
yeah sure
so basically the data format is 800 dimension embeddings
here is some parameters setting for calculating the propensity and labelling


`propensity_attributes = [i for i in range(200)]
propensity_attributes_signs = [1 for i in range(200)]
labeling_model_type = "simple_0.2_0.8"
settings = "lr._.lr._.all"
labeling=0
partition=1

nb_assignments=5
nb_labelings=5`


basically I use the first 200 attributes to calculate the propensity
but the result is all the 5 generated labelling files are 0 everywhere.
is this normal or I don't use the parameters correctly?

**Comment by junchen14** [comment]
I checked the two files which are propensity scores and propensity labelling files
for propensity scores: they are all "nan" everywhere
for propensity labelling: they are all "0" everywhere

which makes me not be able to train the model based on propensity
but I am not clear why that happens, could you give me some tips?
