### ISSUE TITLE
what is sar-e and sar-c

### ISSUE THREAD

**Issue by junchen14** [ML-KULeuven/SAR-PU#2]
Hi,
in the paper, I don't see you mention what is sar-e and sar-c, could you explain a bit about it?

**Comment by jessa** [comment]
Hi, there is no sar-c, it's scar-c.

In SCAR, you make the 'selected completely at random' assumption, which means that the probability of labeling a positive example is independent of its attributes x and this probability is called the label frequency c=Pr(s=1|y=1)=Pr(s=1|y=1, x). Given this assumption, you can use the label frequency c  to convert the dataset to a weighted dataset from which an unbiased model can be learned using standard machine learning methods. This is what the method pu_learn_scar_c does.

In SAR, you make the 'selected at random' assumption, which means that the probability of labeling a positive example is dependent on its attributes x and this conditional probability is called the propensity score e(x) = Pr(s=1|y=1, x). Given this assumption and known propensity scores for your  data, the data can also be converted to a weighted dataset from which an unbiased model can be learned using standard machine learning methods. This is what the method pu_learn_sar_e does. Note that this is a generalization of the SCAR approach, in scar, the propensity scores are just all the same.

In practice, the exact propensity scores e(x) are likely unknown. But if we know on which subset x_e of the attributes x these scores depend, then the EM method can be used: pu_learn_sar_em
